typography_spectrum: 0.5
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.54565
analytics:
  google: null
  facebook: null
  twitter: null
name: folkevision.tv
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Folkevision.tv
    id: daef13a9-6eb5-40e4-9e8f-dbdc450465b0
    type: content
favicon: null
purpose: []
